"""Initial Migrations.

Revision ID: 2309ceba592d
Revises: 
Create Date: 2025-10-25 16:29:19.903161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2309ceba592d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=False),
    sa.Column('isactive', sa.Boolean(), nullable=False),
    sa.Column('createdon', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedon', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('url',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdon', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedon', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_code'), 'url', ['code'], unique=True)
    op.create_index(op.f('ix_url_user'), 'url', ['user'], unique=False)
    op.create_table('url_analytics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('createdon', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedon', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['url'], ['url.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_analytics_url'), 'url_analytics', ['url'], unique=False)
    op.create_index(op.f('ix_url_analytics_user'), 'url_analytics', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_analytics_user'), table_name='url_analytics')
    op.drop_index(op.f('ix_url_analytics_url'), table_name='url_analytics')
    op.drop_table('url_analytics')
    op.drop_index(op.f('ix_url_user'), table_name='url')
    op.drop_index(op.f('ix_url_code'), table_name='url')
    op.drop_table('url')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
