"""added is_superuser field to user model

Revision ID: 33b1ac2a971f
Revises: 1f02536ad273
Create Date: 2025-12-22 17:40:28.107106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b1ac2a971f'
down_revision: Union[str, Sequence[str], None] = '1f02536ad273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default to populate existing rows
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
