"""New Fields in the Visit Tracking Model.

Revision ID: 5c6344a7642c
Revises: 33b1ac2a971f
Create Date: 2025-12-24 12:10:14.299260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6344a7642c'
down_revision: Union[str, Sequence[str], None] = '33b1ac2a971f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_visit', sa.Column('device', sa.VARCHAR(length=30), nullable=True))
    op.add_column('app_visit', sa.Column('browser', sa.VARCHAR(length=30), nullable=True))
    op.add_column('app_visit', sa.Column('os', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_visit', 'os')
    op.drop_column('app_visit', 'browser')
    op.drop_column('app_visit', 'device')
    # ### end Alembic commands ###
