"""added count field in the AppVisit Model.

Revision ID: 6bda414d5381
Revises: 90bc9c07f529
Create Date: 2025-12-25 12:02:34.518788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bda414d5381'
down_revision: Union[str, Sequence[str], None] = '90bc9c07f529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_visit', sa.Column('count', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_visit', 'count')
    # ### end Alembic commands ###
