"""Implemented new visit tracking model.

Revision ID: 8fb06c8079fa
Revises: cf73cd979994
Create Date: 2025-12-21 12:47:34.061578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb06c8079fa'
down_revision: Union[str, Sequence[str], None] = 'cf73cd979994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_visit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', sa.VARCHAR(length=20), nullable=True),
    sa.Column('longitude', sa.VARCHAR(length=20), nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('org', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('createdon', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedon', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_visit_ip_address'), 'app_visit', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_visit_ip_address'), table_name='app_visit')
    op.drop_table('app_visit')
    # ### end Alembic commands ###
