"""add_title_field_to_url_model

Revision ID: 90bc9c07f529
Revises: 49aba142de65
Create Date: 2025-12-25 08:54:00.053733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bc9c07f529'
down_revision: Union[str, Sequence[str], None] = '49aba142de65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('title', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'title')
    # ### end Alembic commands ###
