"""Added is_bot field to separately track bot stats.

Revision ID: cf73cd979994
Revises: fb675eeb3b03
Create Date: 2025-12-17 15:42:51.998028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf73cd979994'
down_revision: Union[str, Sequence[str], None] = 'fb675eeb3b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_analytics', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_analytics', 'is_bot')
    # ### end Alembic commands ###
