"""url code field change.

Revision ID: d087d3e9cc03
Revises: 0dfdb2c171e8
Create Date: 2025-11-13 10:31:53.054663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd087d3e9cc03'
down_revision: Union[str, Sequence[str], None] = '0dfdb2c171e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_url_code'), table_name='url')
    op.create_index(op.f('ix_url_code'), 'url', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_code'), table_name='url')
    op.create_index(op.f('ix_url_code'), 'url', ['code'], unique=True)
    op.alter_column('url', 'code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
