"""url analytics model change.

Revision ID: fb675eeb3b03
Revises: d087d3e9cc03
Create Date: 2025-11-14 11:59:49.139369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb675eeb3b03'
down_revision: Union[str, Sequence[str], None] = 'd087d3e9cc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_analytics', sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True))
    op.add_column('url_analytics', sa.Column('referrer', sa.Text(), nullable=True))
    op.add_column('url_analytics', sa.Column('device', sa.VARCHAR(length=30), nullable=True))
    op.add_column('url_analytics', sa.Column('browser', sa.VARCHAR(length=30), nullable=True))
    op.add_column('url_analytics', sa.Column('os', sa.VARCHAR(length=30), nullable=True))
    op.add_column('url_analytics', sa.Column('user_agent', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_url_analytics_user'), table_name='url_analytics')
    op.drop_constraint(op.f('url_analytics_user_fkey'), 'url_analytics', type_='foreignkey')
    op.drop_column('url_analytics', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_analytics', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('url_analytics_user_fkey'), 'url_analytics', 'user', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('ix_url_analytics_user'), 'url_analytics', ['user'], unique=False)
    op.drop_column('url_analytics', 'user_agent')
    op.drop_column('url_analytics', 'os')
    op.drop_column('url_analytics', 'browser')
    op.drop_column('url_analytics', 'device')
    op.drop_column('url_analytics', 'referrer')
    op.drop_column('url_analytics', 'ip_address')
    # ### end Alembic commands ###
