server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # API
    location /api/ {
        proxy_pass http://app:8000;
    }

    # Short URLs
    location ~ ^/[A-Za-z0-9]{5,}$ {
        proxy_pass http://app:8000;
    }

    # Frontend SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}
